"""criação das tabelas iniciais

Revision ID: 0b1bf64cf3c1
Revises: 
Create Date: 2025-05-28 21:31:43.961304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1bf64cf3c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_ativo'), 'empresas', ['ativo'], unique=False)
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nome'), 'empresas', ['nome'], unique=True)
    op.create_table('frequencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo')
    )
    op.create_index(op.f('ix_maquinas_id'), 'maquinas', ['id'], unique=False)
    op.create_table('origens_problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_origens_problema_id'), 'origens_problema', ['id'], unique=False)
    op.create_table('prioridades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_roles_ativo'), 'roles', ['ativo'], unique=False)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('responsavel_atendimento_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_acao_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('tipo_maquina_id', sa.Integer(), nullable=True),
    sa.Column('origem_id', sa.Integer(), nullable=True),
    sa.Column('datetime_abertura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('porta_ssh', sa.String(length=100), nullable=True),
    sa.Column('relato', sa.Text(), nullable=False),
    sa.Column('prioridade_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('descricao_acao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origem_id'], ['origens_problema.id'], ),
    sa.ForeignKeyConstraint(['prioridade_id'], ['prioridades.id'], ),
    sa.ForeignKeyConstraint(['responsavel_acao_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_atendimento_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['tipo_maquina_id'], ['maquinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamados_ativo'), 'chamados', ['ativo'], unique=False)
    op.create_index(op.f('ix_chamados_cliente'), 'chamados', ['cliente'], unique=False)
    op.create_index(op.f('ix_chamados_datetime_abertura'), 'chamados', ['datetime_abertura'], unique=False)
    op.create_index(op.f('ix_chamados_empresa_id'), 'chamados', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_chamados_id'), 'chamados', ['id'], unique=False)
    op.create_index(op.f('ix_chamados_origem_id'), 'chamados', ['origem_id'], unique=False)
    op.create_index(op.f('ix_chamados_prioridade_id'), 'chamados', ['prioridade_id'], unique=False)
    op.create_index(op.f('ix_chamados_responsavel_acao_id'), 'chamados', ['responsavel_acao_id'], unique=False)
    op.create_index(op.f('ix_chamados_responsavel_atendimento_id'), 'chamados', ['responsavel_atendimento_id'], unique=False)
    op.create_index(op.f('ix_chamados_status_id'), 'chamados', ['status_id'], unique=False)
    op.create_index(op.f('ix_chamados_tipo_maquina_id'), 'chamados', ['tipo_maquina_id'], unique=False)
    op.create_table('chamados_recorrentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('porta_ssh', sa.String(length=100), nullable=True),
    sa.Column('tipo_maquina_id', sa.Integer(), nullable=True),
    sa.Column('relato', sa.Text(), nullable=False),
    sa.Column('prioridade_id', sa.Integer(), nullable=True),
    sa.Column('origem_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_atendimento_id', sa.Integer(), nullable=True),
    sa.Column('responsavel_acao_id', sa.Integer(), nullable=True),
    sa.Column('descricao_acao', sa.Text(), nullable=True),
    sa.Column('frequencia_id', sa.Integer(), nullable=False),
    sa.Column('proxima_execucao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['frequencia_id'], ['frequencias.id'], ),
    sa.ForeignKeyConstraint(['origem_id'], ['origens_problema.id'], ),
    sa.ForeignKeyConstraint(['prioridade_id'], ['prioridades.id'], ),
    sa.ForeignKeyConstraint(['responsavel_acao_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['responsavel_atendimento_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tipo_maquina_id'], ['maquinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamados_recorrentes_ativo'), 'chamados_recorrentes', ['ativo'], unique=False)
    op.create_index(op.f('ix_chamados_recorrentes_id'), 'chamados_recorrentes', ['id'], unique=False)
    op.create_table('log_acoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('chamado_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('data_hora', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('campo', sa.String(), nullable=True),
    sa.Column('valor_antigo', sa.Text(), nullable=True),
    sa.Column('valor_novo', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_acoes_ativo'), 'log_acoes', ['ativo'], unique=False)
    op.create_index(op.f('ix_log_acoes_id'), 'log_acoes', ['id'], unique=False)
    op.add_column('usuarios', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_usuarios_ativo'), 'usuarios', ['ativo'], unique=False)
    op.create_foreign_key(None, 'usuarios', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_column('usuarios', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_index(op.f('ix_usuarios_ativo'), table_name='usuarios')
    op.drop_column('usuarios', 'ativo')
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('usuarios', 'created_at')
    op.drop_column('usuarios', 'role_id')
    op.drop_index(op.f('ix_log_acoes_id'), table_name='log_acoes')
    op.drop_index(op.f('ix_log_acoes_ativo'), table_name='log_acoes')
    op.drop_table('log_acoes')
    op.drop_index(op.f('ix_chamados_recorrentes_id'), table_name='chamados_recorrentes')
    op.drop_index(op.f('ix_chamados_recorrentes_ativo'), table_name='chamados_recorrentes')
    op.drop_table('chamados_recorrentes')
    op.drop_index(op.f('ix_chamados_tipo_maquina_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_status_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_responsavel_atendimento_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_responsavel_acao_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_prioridade_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_origem_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_empresa_id'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_datetime_abertura'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_cliente'), table_name='chamados')
    op.drop_index(op.f('ix_chamados_ativo'), table_name='chamados')
    op.drop_table('chamados')
    op.drop_table('status')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_ativo'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('prioridades')
    op.drop_index(op.f('ix_origens_problema_id'), table_name='origens_problema')
    op.drop_table('origens_problema')
    op.drop_index(op.f('ix_maquinas_id'), table_name='maquinas')
    op.drop_table('maquinas')
    op.drop_table('frequencias')
    op.drop_index(op.f('ix_empresas_nome'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_ativo'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
