"""add dias field to frequencias table

Revision ID: 47e3c783e8d8
Revises: 0b1bf64cf3c1
Create Date: 2025-05-28 23:46:42.682076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e3c783e8d8'
down_revision: Union[str, None] = '0b1bf64cf3c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frequencias', sa.Column('dias', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frequencias', 'dias')
    # ### end Alembic commands ###
