"""add ativo column to OrigemProblema

Revision ID: 527466268e73
Revises: 902083046a94
Create Date: 2025-06-03 16:22:55.798150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527466268e73'
down_revision: Union[str, None] = '902083046a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('origens_problema', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('origens_problema', 'ativo')
    # ### end Alembic commands ###
