"""Add 'contato', rename 'descricao_acao' to 'acao_realizada' and remove 'cliente' from Chamado and ChamadoRecorrente

Revision ID: 7146ac2d076e
Revises: 527466268e73
Create Date: 2025-06-07 10:20:45.010682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7146ac2d076e'
down_revision: Union[str, None] = '527466268e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamados', sa.Column('contato', sa.String(length=150), nullable=False))
    op.add_column('chamados', sa.Column('acao_realizada', sa.Text(), nullable=True))
    op.alter_column('chamados', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chamados', 'datetime_abertura',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_chamados_cliente'), table_name='chamados')
    op.create_index(op.f('ix_chamados_contato'), 'chamados', ['contato'], unique=False)
    op.drop_column('chamados', 'cliente')
    op.drop_column('chamados', 'descricao_acao')
    op.add_column('chamados_recorrentes', sa.Column('acao_realizada', sa.Text(), nullable=True))
    op.drop_column('chamados_recorrentes', 'descricao_acao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chamados_recorrentes', sa.Column('descricao_acao', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('chamados_recorrentes', 'acao_realizada')
    op.add_column('chamados', sa.Column('descricao_acao', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chamados', sa.Column('cliente', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chamados_contato'), table_name='chamados')
    op.create_index(op.f('ix_chamados_cliente'), 'chamados', ['cliente'], unique=False)
    op.alter_column('chamados', 'datetime_abertura',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('chamados', 'empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('chamados', 'acao_realizada')
    op.drop_column('chamados', 'contato')
    # ### end Alembic commands ###
