"""adiciona updated_at na tabela interacao

Revision ID: dc81e5a61082
Revises: 5d548f00872c
Create Date: 2025-11-06 16:35:11.560673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc81e5a61082'
down_revision: Union[str, None] = '5d548f00872c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interacoes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interacoes', 'updated_at')
    # ### end Alembic commands ###
