"""Adiciona tabelas Anexos, Interacoes e Tags

Revision ID: de5c724ec2d9
Revises: 7146ac2d076e
Create Date: 2025-08-23 02:29:34.332915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5c724ec2d9'
down_revision: Union[str, None] = '7146ac2d076e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo_original', sa.String(length=255), nullable=False),
    sa.Column('path_arquivo_armazenado', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('data_upload', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_arquivo_armazenado')
    )
    op.create_index(op.f('ix_anexos_ativo'), 'anexos', ['ativo'], unique=False)
    op.create_index(op.f('ix_anexos_id'), 'anexos', ['id'], unique=False)
    op.create_table('chamados_tags',
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('chamado_id', 'tag_id')
    )
    op.create_table('interacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('privado', sa.Boolean(), nullable=False),
    sa.Column('data_interacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacoes_ativo'), 'interacoes', ['ativo'], unique=False)
    op.create_index(op.f('ix_interacoes_id'), 'interacoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interacoes_id'), table_name='interacoes')
    op.drop_index(op.f('ix_interacoes_ativo'), table_name='interacoes')
    op.drop_table('interacoes')
    op.drop_table('chamados_tags')
    op.drop_index(op.f('ix_anexos_id'), table_name='anexos')
    op.drop_index(op.f('ix_anexos_ativo'), table_name='anexos')
    op.drop_table('anexos')
    op.drop_table('tags')
    # ### end Alembic commands ###
